version: "3.7"

networks:
    my-network-1:
        external: true

services:
    payment-api:
        hostname: payment-api
        container_name: payment-service-api
        build:
            context: .
            target: development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3001:3001
        command: npm run start:dev
        env_file:
            - .env.dev
        depends_on:
            - payment-db
        networks:
            - my-network-1
    payment-db:
        container_name: payment-service-db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3308:3306"
        networks:
            - my-network-1
        volumes:
            - payment-service-db:/var/lib/mysql

# Names our volume
volumes:
    payment-service-db:
